;;; completions.lisp
;;;
;;; SPDX-License-Identifier: MIT
;;;
;;; Copyright (C) 2026 Anthony Green

(in-package #:scute)

;;; Shell completions, written from the command tree rather than beside it.
;;;
;;; A completion script maintained by hand drifts from the tool the first time
;;; an option is added and nobody notices until someone presses tab.  These are
;;; generated from the same command objects the CLI is built from, so a new
;;; option is completable the moment it exists.

(defun command-tree ()
  "Every command, as (NAME DESCRIPTION OPTION ...) with the top level first."
  (let ((application (make-app)))
    (cons (list nil (clingon:command-description application)
                (clingon:command-options application))
          (mapcar (lambda (command)
                    (list (clingon:command-name command)
                          (clingon:command-description command)
                          (clingon:command-options command)))
                  (clingon:command-sub-commands application)))))

(defun quotable (text)
  "TEXT with the characters that would end a shell's quoting removed.
A description carrying an apostrophe -- \"scute's own commands\" -- closes the
single quote it sits inside and leaves the completion script unparsable."
  (substitute #\Space #\' (substitute #\Space #\" (or text ""))))

(defun option-flags (option)
  "The spellings OPTION answers to, longest first."
  (remove nil
          (list (let ((long (clingon:option-long-name option)))
                  (and long (format nil "--~A" long)))
                (let ((short (clingon:option-short-name option)))
                  (and short (format nil "-~A" short))))))

(defun visible-options (entry)
  "The options worth offering: not the ones the usage page hides either."
  (remove-if #'clingon:option-hidden-p (third entry)))

(defun command-flags (entry)
  (loop for option in (visible-options entry) append (option-flags option)))

(defun subcommand-entries (tree)
  (remove nil tree :key #'first))

(defun takes-a-path-p (option)
  "Whether completing OPTION's value with filenames is the useful thing."
  (let ((long (clingon:option-long-name option)))
    (and long (member long '("policy" "output" "read" "read-execute" "read-write"
                             "read-write-execute")
                      :test #'string=))))

(defun path-taking-flags (entry)
  (loop for option in (visible-options entry)
        when (takes-a-path-p option)
          append (option-flags option)))

;;── bash ───────────────────────────────────────────────────────────────────────

(defparameter +bash-completion-preamble+
  '("_scute() {"
    "  local cur prev command i"
    "  cur=\"${COMP_WORDS[COMP_CWORD]}\""
    "  prev=\"${COMP_WORDS[COMP_CWORD-1]}\""
    "  command=\"\""
    "  for ((i=1; i < COMP_CWORD; i++)); do"
    "    case \"${COMP_WORDS[i]}\" in"
    "      -*) ;;"
    "      *) command=\"${COMP_WORDS[i]}\"; break ;;"
    "    esac"
    "  done"
    ""
    "  # Past a --, the words belong to the sandboxed command, not to scute."
    "  for ((i=1; i < COMP_CWORD; i++)); do"
    "    if [ \"${COMP_WORDS[i]}\" = \"--\" ]; then"
    "      COMPREPLY=( $(compgen -c -- \"$cur\") )"
    "      return 0"
    "    fi"
    "  done"
    "")
  "The part of the bash script that does not depend on what scute can do.")

(defun write-bash-completions (tree stream)
  (format stream "# scute completions for bash.  Generated by 'scute completions bash'.~%~%")
  (format stream "~{~A~%~}" +bash-completion-preamble+)
  (format stream "  case \"$prev\" in~%    ~{~A~^|~})~%      COMPREPLY=( $(compgen -f -- \"$cur\") )~%      return 0~%      ;;~%  esac~%~%"
          (remove-duplicates (loop for entry in tree append (path-taking-flags entry))
                             :test #'string=))
  (format stream "  case \"$command\" in~%")
  (dolist (entry (subcommand-entries tree))
    (format stream "    ~A) COMPREPLY=( $(compgen -W \"~{~A~^ ~}\" -- \"$cur\") ) ;;~%"
            (first entry) (command-flags entry)))
  (format stream "    *) COMPREPLY=( $(compgen -W \"~{~A~^ ~} ~{~A~^ ~}\" -- \"$cur\") ) ;;~%"
          (mapcar #'first (subcommand-entries tree))
          (command-flags (first tree)))
  (format stream "  esac~%}~%~%complete -F _scute scute~%"))

;;── zsh ────────────────────────────────────────────────────────────────────────

(defun write-zsh-completions (tree stream)
  (format stream "#compdef scute~%# Generated by 'scute completions zsh'.~%~%")
  (format stream "_scute() {~%  local -a commands~%  commands=(~%")
  (dolist (entry (subcommand-entries tree))
    (format stream "    '~A:~A'~%" (first entry) (quotable (second entry))))
  (format stream "  )~%~%  _arguments -C '1: :->command' '*:: :->argument'~%~%")
  (format stream "  case $state in~%    command) _describe 'scute command' commands ;;~%    \
argument)~%      case $words[1] in~%")
  (dolist (entry (subcommand-entries tree))
    (format stream "        ~A) _arguments ~{'~A[~A]'~^ ~} '*:file:_files' ;;~%"
            (first entry)
            (loop for option in (visible-options entry)
                  append (list (first (option-flags option))
                               (quotable (clingon:option-description option))))))
  (format stream "      esac ;;~%  esac~%}~%~%_scute \"$@\"~%"))

;;── fish ───────────────────────────────────────────────────────────────────────

(defun write-fish-completions (tree stream)
  (format stream "# scute completions for fish.  Generated by 'scute completions fish'.~%~%")
  (format stream "complete -c scute -f~%")
  (dolist (entry (subcommand-entries tree))
    (format stream "complete -c scute -n '__fish_use_subcommand' -a '~A' -d '~A'~%"
            (first entry) (quotable (second entry))))
  (dolist (entry tree)
    (dolist (option (visible-options entry))
      (let ((long (clingon:option-long-name option))
            (short (clingon:option-short-name option))
            (condition (if (first entry)
                           (format nil "__fish_seen_subcommand_from ~A" (first entry))
                           "not __fish_seen_subcommand_from run learn check doctor completions")))
        (when long
          (format stream "complete -c scute -n '~A'~@[ -s ~A~] -l ~A~:[~; -r -F~] -d '~A'~%"
                  condition short long (takes-a-path-p option)
                  (quotable (clingon:option-description option))))))))

(defun write-completions (shell &optional (stream *standard-output*))
  "Write completions for SHELL, or refuse a shell Scute does not know."
  (let ((tree (command-tree)))
    (cond ((string-equal shell "bash") (write-bash-completions tree stream))
          ((string-equal shell "zsh") (write-zsh-completions tree stream))
          ((string-equal shell "fish") (write-fish-completions tree stream))
          (t (usage-error (format nil "no completions for ~S; scute knows bash, ~
                                       zsh, and fish"
                                  shell))))
    shell))
