;;; completions.lisp
;;;
;;; SPDX-License-Identifier: MIT
;;;
;;; Copyright (C) 2026 Anthony Green

(in-package #:scute)

;;; Shell completions, written from the command tree rather than beside it.
;;;
;;; A completion script maintained by hand drifts from the tool the first time
;;; an option is added and nobody notices until someone presses tab.  These are
;;; generated from the same command objects the CLI is built from, so a new
;;; option is completable the moment it exists.

(defun command-tree ()
  "Every command, as (NAME DESCRIPTION OPTION ...) with the top level first."
  (let ((application (make-app)))
    (cons (list nil (clingon:command-description application)
                (clingon:command-options application))
          (mapcar (lambda (command)
                    (list (clingon:command-name command)
                          (clingon:command-description command)
                          (clingon:command-options command)))
                  (clingon:command-sub-commands application)))))

(defun quotable (text)
  "TEXT with the characters that would end a shell's quoting removed.
A description carrying an apostrophe -- \"scute's own commands\" -- closes the
single quote it sits inside and leaves the completion script unparsable."
  (substitute #\Space #\' (substitute #\Space #\" (or text ""))))

(defun option-flags (option)
  "The spellings OPTION answers to, longest first."
  (remove nil
          (list (let ((long (clingon:option-long-name option)))
                  (and long (format nil "--~A" long)))
                (let ((short (clingon:option-short-name option)))
                  (and short (format nil "-~A" short))))))

(defun visible-options (entry)
  "The options worth offering: not the ones the usage page hides either."
  (remove-if #'clingon:option-hidden-p (third entry)))

(defun command-flags (entry)
  (loop for option in (visible-options entry) append (option-flags option)))

(defun subcommand-entries (tree)
  (remove nil tree :key #'first))

(defun takes-a-path-p (option)
  "Whether completing OPTION's value with filenames is the useful thing."
  (let ((long (clingon:option-long-name option)))
    (and long (member long '("policy" "output" "read" "read-execute" "read-write"
                             "read-write-execute")
                      :test #'string=))))

(defun path-taking-flags (entry)
  (loop for option in (visible-options entry)
        when (takes-a-path-p option)
          append (option-flags option)))

;;── bash ───────────────────────────────────────────────────────────────────────

(defparameter +bash-completion-preamble+
  '("_scute() {"
    "  local cur prev command i"
    "  cur=\"${COMP_WORDS[COMP_CWORD]}\""
    "  prev=\"${COMP_WORDS[COMP_CWORD-1]}\""
    "  command=\"\""
    "  for ((i=1; i < COMP_CWORD; i++)); do"
    "    case \"${COMP_WORDS[i]}\" in"
    "      -*) ;;"
    "      *) command=\"${COMP_WORDS[i]}\"; break ;;"
    "    esac"
    "  done"
    ""
    "  # Past a --, the words belong to the sandboxed command, not to scute."
    "  for ((i=1; i < COMP_CWORD; i++)); do"
    "    if [ \"${COMP_WORDS[i]}\" = \"--\" ]; then"
    "      COMPREPLY=( $(compgen -c -- \"$cur\") )"
    "      return 0"
    "    fi"
    "  done"
    "")
  "The part of the bash script that does not depend on what scute can do.")

(defun write-bash-completions (tree stream)
  (format stream "# scute completions for bash.  Generated by 'scute completions bash'.~%~%")
  (format stream "~{~A~%~}" +bash-completion-preamble+)
  (format stream "  case \"$prev\" in~%    ~{~A~^|~})~%      COMPREPLY=( $(compgen -f -- \"$cur\") )~%      return 0~%      ;;~%  esac~%~%"
          (remove-duplicates (loop for entry in tree append (path-taking-flags entry))
                             :test #'string=))
  (format stream "  case \"$command\" in~%")
  (dolist (entry (subcommand-entries tree))
    (format stream "    ~A) COMPREPLY=( $(compgen -W \"~{~A~^ ~}\" -- \"$cur\") ) ;;~%"
            (first entry) (command-flags entry)))
  (format stream "    *) COMPREPLY=( $(compgen -W \"~{~A~^ ~} ~{~A~^ ~}\" -- \"$cur\") ) ;;~%"
          (mapcar #'first (subcommand-entries tree))
          (command-flags (first tree)))
  (format stream "  esac~%}~%~%complete -F _scute scute~%"))

;;── zsh ────────────────────────────────────────────────────────────────────────

(defun write-zsh-completions (tree stream)
  (format stream "#compdef scute~%# Generated by 'scute completions zsh'.~%~%")
  (format stream "_scute() {~%  local -a commands~%  commands=(~%")
  (dolist (entry (subcommand-entries tree))
    (format stream "    '~A:~A'~%" (first entry) (quotable (second entry))))
  (format stream "  )~%~%  _arguments -C '1: :->command' '*:: :->argument'~%~%")
  (format stream "  case $state in~%    command) _describe 'scute command' commands ;;~%    \
argument)~%      case $words[1] in~%")
  (dolist (entry (subcommand-entries tree))
    (format stream "        ~A) _arguments ~{'~A[~A]'~^ ~} '*:file:_files' ;;~%"
            (first entry)
            (loop for option in (visible-options entry)
                  append (list (first (option-flags option))
                               (quotable (clingon:option-description option))))))
  (format stream "      esac ;;~%  esac~%}~%~%_scute \"$@\"~%"))

;;── fish ───────────────────────────────────────────────────────────────────────

(defun write-fish-completions (tree stream)
  (format stream "# scute completions for fish.  Generated by 'scute completions fish'.~%~%")
  (format stream "complete -c scute -f~%")
  (dolist (entry (subcommand-entries tree))
    (format stream "complete -c scute -n '__fish_use_subcommand' -a '~A' -d '~A'~%"
            (first entry) (quotable (second entry))))
  (dolist (entry tree)
    (dolist (option (visible-options entry))
      (let ((long (clingon:option-long-name option))
            (short (clingon:option-short-name option))
            (condition (if (first entry)
                           (format nil "__fish_seen_subcommand_from ~A" (first entry))
                           "not __fish_seen_subcommand_from run learn check doctor completions")))
        (when long
          (format stream "complete -c scute -n '~A'~@[ -s ~A~] -l ~A~:[~; -r -F~] -d '~A'~%"
                  condition short long (takes-a-path-p option)
                  (quotable (clingon:option-description option))))))))

(defun write-completions (shell &optional (stream *standard-output*))
  "Write completions for SHELL, or refuse a shell Scute does not know."
  (let ((tree (command-tree)))
    (cond ((string-equal shell "bash") (write-bash-completions tree stream))
          ((string-equal shell "zsh") (write-zsh-completions tree stream))
          ((string-equal shell "fish") (write-fish-completions tree stream))
          (t (usage-error (format nil "no completions for ~S; scute knows bash, ~
                                       zsh, and fish"
                                  shell))))
    shell))

;;── A manual page ──────────────────────────────────────────────────────────────
;;
;;; Generated from the same command tree, for the same reason: a manual page
;;; written beside a tool describes the tool as it was.

(defun roff-escape (text)
  "TEXT with the characters roff would read as markup made harmless."
  (with-output-to-string (stream)
    (loop for character across (or text "")
          do (case character
               (#\\ (write-string "\\e" stream))
               (#\- (write-string "\\-" stream))
               (t (write-char character stream))))))

(defun write-manual-options (entry stream)
  (dolist (option (visible-options entry))
    (let ((long (clingon:option-long-name option))
          (short (clingon:option-short-name option)))
      (when long
        (format stream ".TP~%")
        ;; Bold the spellings, italic the argument: that is what man pages do,
        ;; and it makes --read PATH read as one option taking a value rather
        ;; than as a flag with a stray word beside it.
        (format stream ".BR ~@[\\-~A \", \" ~]\\-\\-~A~@[ \" \" \\fI~A\\fR~]~%"
                short (roff-escape long)
                (and (clingon:option-parameter option)
                     (roff-escape (clingon:option-parameter option))))
        (format stream "~A.~%"
                (roff-escape (clingon:option-description option)))))))

(defun write-manual-examples (command stream)
  (let ((examples (clingon:command-examples command)))
    (when examples
      (loop for (description . line) in examples
            do (format stream ".PP~%~A~%.PP~%.EX~%~A~%.EE~%"
                       (roff-escape description) (roff-escape line))))))

(defun write-manual-page (stream &key (date "2026-09-18") (version "0.1.0"))
  "Write the scute manual page, in roff, from scute's own commands."
  (let* ((application (make-app))
         (tree (command-tree)))
    (format stream ".\\\" Generated by 'scute man'.  Do not edit.~%")
    (format stream ".TH SCUTE 1 \"~A\" \"scute ~A\" \"User Commands\"~%" date version)
    (format stream ".SH NAME~%scute \\- run one command inside a deny\\-by\\-default Linux sandbox~%")
    (format stream ".SH SYNOPSIS~%.B scute~%.RI [ command ]~%.RI [ options ]~%~
                    .RI [ arguments ]~%")
    (format stream ".SH DESCRIPTION~%~
                    Scute runs one local command inside a sandbox built from Landlock, ~
                    namespaces, seccomp and cgroup v2.  It is a native sandbox rather ~
                    than a container or a virtual machine: one executable, no privileged ~
                    daemon, and a parent that establishes every requested control before ~
                    it releases the child that becomes the command.~%.PP~%~
                    A host that cannot provide a control the policy asks for receives an ~
                    error instead of a weaker sandbox.  Scute shares the host kernel and ~
                    does not claim to contain kernel exploits.~%")
    (format stream ".SH COMMANDS~%")
    (dolist (entry (subcommand-entries tree))
      (format stream ".TP~%.B ~A~%~A.~%" (first entry) (roff-escape (second entry))))
    ;; clingon fills a top-level command's default options in at parse time, so
    ;; there may be nothing here; an empty section is worse than no section.
    (when (visible-options (first tree))
      (format stream ".SH GLOBAL OPTIONS~%")
      (write-manual-options (first tree) stream))
    (dolist (command (clingon:command-sub-commands application))
      (let ((entry (find (clingon:command-name command) tree
                         :key #'first :test #'equal)))
        (format stream ".SH ~:@(~A~)~%" (clingon:command-name command))
        (let ((usage (clingon:command-usage command)))
          (when (and usage (plusp (length usage)))
            (format stream ".PP~%.B scute ~A~%~A~%"
                    (clingon:command-name command) (roff-escape usage))))
        (write-manual-options entry stream)
        (write-manual-examples command stream)))
    (format stream ".SH EXIT STATUS~%~
                    .TP~%.B 0\\-125~%The command's own exit status.~%~
                    .TP~%.B 64~%The command line asked for something impossible.~%~
                    .TP~%.B 65~%The policy is not one Scute will accept.~%~
                    .TP~%.B 126~%The command exists but could not be executed.~%~
                    .TP~%.B 127~%The command does not exist.~%~
                    .TP~%.B 128+n~%A signal ended the command.~%~
                    .TP~%.B 1~%A control this host could not establish.~%")
    (format stream ".SH SEE ALSO~%~
                    .BR landlock (7),~%.BR seccomp (2),~%.BR user_namespaces (7),~%~
                    .BR cgroups (7)~%")
    (format stream ".SH AUTHOR~%~{~A~^, ~}~%"
            (mapcar #'roff-escape (clingon:command-authors application)))
    t))
